### ISSUE TITLE
A typing error in misc/nginx-openstack/service.yaml

### ISSUE THREAD

**Issue by philippemerle** [xlab-si/xopera-examples#35]
[misc/nginx-openstack/service.yaml](https://github.com/xlab-si/xopera-examples/blob/master/misc/nginx-openstack/service.yaml) defines the two following node templates:
```
...
topology_template:
  node_templates:
    nginx:
      type: nginx.Server
      requirements:
        - host: vm
...
    site:
      type: nginx.Site
      requirements:
        - host: nginx
```

As the `nginx.Site` node type derived from the `tosca.nodes.SoftwareComponent` node type, the expected `node` type for the `host` requirement of the `site` node template shall be `tosca.nodes.Compute`. But the given `nginx` node template is of type `tosca.nodes.SoftwareComponent`, which does not derive from `tosca.nodes.Compute`. So there is a typing error.

The simplest solution to correct this typing error is to make `nginx.Site` deriving from `tosca.nodes.Root` instead of deriving from `tosca.nodes.SoftwareComponent`. This solution was already used into TOSCA normative types where both `tosca.nodes.Database` and `tosca.nodes.WebApplication` derive from `tosca.nodes.Root`, even if they are conceptually software components (sic!).

Another solution is to modify TOSCA normative types, but this is another story;-)
