### ISSUE TITLE
Typing errors in tosca/capability-attributes-properties/service.yaml

### ISSUE THREAD

**Issue by philippemerle** [xlab-si/xopera-examples#40]
[Section 3.7.2 of TOSCA 1.3](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_ELEMENT_CAPABILITY_DEFN) specifies the grammar of capability definition. However the semantics of capability property and attribute definitions is not well-defined:

1. could one **only refine** properties and attributes defined into the capability type? 
2. could one **both refine and add** new properties or attributes not defined into the capability type?

xOpera opera seems to implement the second semantics, doesn't it?

However some sentences in the TOSCA 1.3 specification could give the impression that only the first semantics is allowed:

* _without further refinement of the capability type definitions_
* _The Capability Type, in this example MyCapabilityTypeName, would be defined elsewhere and have an integer property named limit._

This ambiguity was fixed in [Section 4.3.5.2 of TOSCA 2.0](https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd03/TOSCA-v2.0-csd03.html#_Toc56506365): only the refinement semantics should be supported, the add semantics shall be not allowed.

If you agree on the refinement semantics only, then [tosca/capability-attributes-properties/service.yaml](https://github.com/xlab-si/xopera-examples/blob/master/tosca/capability-attributes-properties/service.yaml) contains two typing errors:

```
...
my_second_node_type:
    ...
    capabilities:
      my_capability:
        type: tosca.capabilities.Root
        attributes:
          capability_attribute: # ERROR: capability_attribute undefined in tosca.capabilities.Root
            type: string
        properties:
          capability_property: # ERROR: capability_property undefined in tosca.capabilities.Root
            type: string
```

@anzoman What do you think about this?
