### ISSUE TITLE
assigning a value expression to the default of a property/parameter/attribute definition is not allowed by TOSCA

### ISSUE THREAD

**Issue by philippemerle** [xlab-si/xopera-examples#42]
The TOSCA 1.3 grammar allows one to assign **a default value** to a property/attribute/parameter definition, see Sections 3.6.10.4, 3.6.12.3, and 3.6.14.2. But I found no assigment of **a default value expression** such as a `concat`/`join`/`token`/`get_property`/`get_attribute`/... function call in the TOSCA 1.3 specification. Conceptually, the default value of a property/attribute/parameter definition is a simple (or complex) constant such as `1`, `true`, `hello`, `10 s`, `20 Hz`, `[ 1, 2, 3 ]`, `{ x: 10, y: 20 }`, ...

However, I found **around 300 assigments of a default value expression** across all xOpera examples.
For this finding and all my previous issues, I found them automatically with our [TOSCA toolbox](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox).

Is it an expected specific xOpera feature or a misinterpretation of the TOSCA specification?

**Comment by anzoman** [comment]
@philippemerle ok, so according to TOSCA for instance `default: { get_property: [ SELF, my_property ] }` is not a valid default value assignment because we're using `get_property` TOSCA function, which is a value expression? If this is the case then we probably have a misinterpretation of the TOSCA specification here.

Also thanks for linking your [TOSCA toolbox](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox), we'll take a look.

**Comment by philippemerle** [comment]
> according to TOSCA for instance default: { get_property: [ SELF, my_property ] } is not a valid default value assignment because we're using get_property TOSCA function, which is a value expression?

yes this is not a valid default value assignment because `{ get_property: [ SELF, my_property ] }` is an expression.

**Comment by philippemerle** [comment]
I started to correct this on xopera-opera : see https://github.com/xlab-si/xopera-opera/issues/225 and https://github.com/philippemerle/xopera-opera/commit/fb20330f5aab06f38e6c6a8032a46e7a92617e08

**Comment by anzoman** [comment]
Great @philippemerle, thanks for fixing this.

**Comment by philippemerle** [comment]
I corrected all the errors related to default assignments (see https://github.com/xlab-si/xopera-examples/pull/49) except for two default assignments in [tosca/intrinsic-functions/service.yaml](https://github.com/xlab-si/xopera-examples/blob/master/tosca/intrinsic-functions/service.yaml):
```
  hello_type_3:
    derived_from: tosca.nodes.SoftwareComponent
    attributes:
      attribute3_2:
        type: string
        default: { join: [ [ "a", "t", "t", "r", "i", "b", "u", "t", "e" ] ] } # ERROR 1
    properties:
      property3_2:
        type: string
        default: { concat: [ 'Property: ', get_attribute: [ SELF, attribute3_2 ] ] } # ERROR 2
```
Here, `default` could not be replaced by `value` because `value` is not a valid keyname for both attribute and property definitions in TOSCA 1.3. You should revisit the design/implementation of this example to correct these two errors.

Just for information, TOSCA 2.0 makes `value` a valid keyname for both attribute and property definitions.
