### ISSUE TITLE
Typing error in misc/compare-templates/lib/types.yaml

### ISSUE THREAD

**Issue by philippemerle** [xlab-si/xopera-examples#45]
[misc/compare-templates/lib/types.yaml](https://github.com/xlab-si/xopera-examples/blob/master/misc/compare-templates/lib/types.yaml) contains the following definition:
```
node_types:
  hello_type:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      ...
      test_map:
        default:
        type: map
```
The `default` value is equals to `null` and it is not compatible with `type: map`.

`default:` should be replaced by `default: {}`.
